export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const LOAD_BLOCKCHAIN = 'LOAD_BLOCKCHAIN';
export const START_LOADING_BLOCKCHAIN = 'START_LOADING_BLOCKCHAIN';
export const BLOCKCHAIN_FAILED = 'BLOCKCHAIN_FAILED';
